### ISSUE TITLE
Error with 'bash setup.sh'

### ISSUE THREAD

**Issue by ujwalakoriraj** [csyxwei/FFWM#2]
Running the command "bash setup.sh", gives the following long error. Please help.
.........
which: no hipcc in (/c/Users/rajak/anaconda3/envs/ff/lib/site-packages/torch/lib:/c/Users/rajak/anaconda3/envs/ff/Library/bin:/c/Users/rajak/anaconda3/envs/ff:/c/Users/rajak/anaconda3/envs/ff/Library/mingw-w64/bin:/c/Users/rajak/anaconda3/envs/ff/Library/usr/bin:/c/Users/rajak/anaconda3/envs/ff/Library/bin:/c/Users/rajak/anaconda3/envs/ff/Scripts:/c/Users/rajak/anaconda3/envs/ff/bin:/c/Users/rajak/anaconda3/condabin:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/bin:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/libnvvp:/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/ProgramData/chocolatey/bin:/c/Program Files/NVIDIA Corporation/Nsight Compute 2019.4.0:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/extras/CUPTI/lib64:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include:/c/tools/cuda/bin:/c/tools/TensorRT-6.0.1.5:/c/Program Files/CMake/bin:/usr/bin:/c/opencv-master/cmake:.)
running develop
running egg_info
writing block_extractor_cuda.egg-info\PKG-INFO
writing dependency_links to block_extractor_cuda.egg-info\dependency_links.txt
writing top-level names to block_extractor_cuda.egg-info\top_level.txt
reading manifest file 'block_extractor_cuda.egg-info\SOURCES.txt'
writing manifest file 'block_extractor_cuda.egg-info\SOURCES.txt'
running build_ext
C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\utils\cpp_extension.py:237: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'block_extractor_cuda' extension
Emitting ninja build file D:\python\projects\reidentification\face_frontalization\frontalization-master\2_FFWM-master\cuda\block_extractor\build\temp.win-amd64-3.7\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -IC:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\include -IC:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\include\TH -IC:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -IC:\Users\rajak\anaconda3\envs\ff\include -IC:\Users\rajak\anaconda3\envs\ff\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c D:\python\projects\reidentification\face_frontalization\frontalization-master\2_FFWM-master\cuda\block_extractor\block_extractor_cuda.cc /FoD:\python\projects\reidentification\face_frontalization\frontalization-master\2_FFWM-master\cuda\block_extractor\build\temp.win-amd64-3.7\Release\block_extractor_cuda.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=block_extractor_cuda -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
FAILED: D:/python/projects/reidentification/face_frontalization/frontalization-master/2_FFWM-master/cuda/block_extractor/build/temp.win-amd64-3.7/Release/block_extractor_cuda.obj
cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -IC:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\include -IC:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\include\TH -IC:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -IC:\Users\rajak\anaconda3\envs\ff\include -IC:\Users\rajak\anaconda3\envs\ff\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c D:\python\projects\reidentification\face_frontalization\frontalization-master\2_FFWM-master\cuda\block_extractor\block_extractor_cuda.cc /FoD:\python\projects\reidentification\face_frontalization\frontalization-master\2_FFWM-master\cuda\block_extractor\build\temp.win-amd64-3.7\Release\block_extractor_cuda.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=block_extractor_cuda -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
CreateProcess failed: The system cannot find the file specified.
ninja: fatal: ReadFile: The handle is invalid.

Traceback (most recent call last):
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\utils\cpp_extension.py", line 1400, in _run_ninja_build    check=True)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 34, in <module>
    'build_ext': BuildExtension
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\rajak\anaconda3\envs\ff\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\setuptools\command\develop.py", line 34, in run
    self.install_for_development()
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\setuptools\command\develop.py", line 136, in install_for_development
    self.run_command('build_ext')
  File "C:\Users\rajak\anaconda3\envs\ff\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\utils\cpp_extension.py", line 580, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\rajak\anaconda3\envs\ff\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\distutils\command\build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\utils\cpp_extension.py", line 562, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\utils\cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\utils\cpp_extension.py", line 1413, in _run_ninja_build    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension
which: no hipcc in (/c/Users/rajak/anaconda3/envs/ff/lib/site-packages/torch/lib:/c/Users/rajak/anaconda3/envs/ff/Library/bin:/c/Users/rajak/anaconda3/envs/ff:/c/Users/rajak/anaconda3/envs/ff/Library/mingw-w64/bin:/c/Users/rajak/anaconda3/envs/ff/Library/usr/bin:/c/Users/rajak/anaconda3/envs/ff/Library/bin:/c/Users/rajak/anaconda3/envs/ff/Scripts:/c/Users/rajak/anaconda3/envs/ff/bin:/c/Users/rajak/anaconda3/condabin:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/bin:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/libnvvp:/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/ProgramData/chocolatey/bin:/c/Program Files/NVIDIA Corporation/Nsight Compute 2019.4.0:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/extras/CUPTI/lib64:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include:/c/tools/cuda/bin:/c/tools/TensorRT-6.0.1.5:/c/Program Files/CMake/bin:/usr/bin:/c/opencv-master/cmake:.)
running develop
running egg_info
writing local_attn_reshape_cuda.egg-info\PKG-INFO
writing dependency_links to local_attn_reshape_cuda.egg-info\dependency_links.txt
writing top-level names to local_attn_reshape_cuda.egg-info\top_level.txt
reading manifest file 'local_attn_reshape_cuda.egg-info\SOURCES.txt'
writing manifest file 'local_attn_reshape_cuda.egg-info\SOURCES.txt'
running build_ext
C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\utils\cpp_extension.py:237: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'local_attn_reshape_cuda' extension
Emitting ninja build file D:\python\projects\reidentification\face_frontalization\frontalization-master\2_FFWM-master\cuda\local_attn_reshape\build\temp.win-amd64-3.7\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -IC:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\include -IC:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\include\TH -IC:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -IC:\Users\rajak\anaconda3\envs\ff\include -IC:\Users\rajak\anaconda3\envs\ff\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c D:\python\projects\reidentification\face_frontalization\frontalization-master\2_FFWM-master\cuda\local_attn_reshape\local_attn_reshape_cuda.cc /FoD:\python\projects\reidentification\face_frontalization\frontalization-master\2_FFWM-master\cuda\local_attn_reshape\build\temp.win-amd64-3.7\Release\local_attn_reshape_cuda.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=local_attn_reshape_cuda -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
FAILED: D:/python/projects/reidentification/face_frontalization/frontalization-master/2_FFWM-master/cuda/local_attn_reshape/build/temp.win-amd64-3.7/Release/local_attn_reshape_cuda.obj
cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -IC:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\include -IC:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\include\TH -IC:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -IC:\Users\rajak\anaconda3\envs\ff\include -IC:\Users\rajak\anaconda3\envs\ff\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c D:\python\projects\reidentification\face_frontalization\frontalization-master\2_FFWM-master\cuda\local_attn_reshape\local_attn_reshape_cuda.cc /FoD:\python\projects\reidentification\face_frontalization\frontalization-master\2_FFWM-master\cuda\local_attn_reshape\build\temp.win-amd64-3.7\Release\local_attn_reshape_cuda.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=local_attn_reshape_cuda -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
CreateProcess failed: The system cannot find the file specified.
ninja: fatal: ReadFile: The handle is invalid.

Traceback (most recent call last):
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\utils\cpp_extension.py", line 1400, in _run_ninja_build    check=True)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    'build_ext': BuildExtension
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\rajak\anaconda3\envs\ff\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\setuptools\command\develop.py", line 34, in run
    self.install_for_development()
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\setuptools\command\develop.py", line 136, in install_for_development
    self.run_command('build_ext')
  File "C:\Users\rajak\anaconda3\envs\ff\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\utils\cpp_extension.py", line 580, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\rajak\anaconda3\envs\ff\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\distutils\command\build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\utils\cpp_extension.py", line 562, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\utils\cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\utils\cpp_extension.py", line 1413, in _run_ninja_build    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension
which: no hipcc in (/c/Users/rajak/anaconda3/envs/ff/lib/site-packages/torch/lib:/c/Users/rajak/anaconda3/envs/ff/Library/bin:/c/Users/rajak/anaconda3/envs/ff:/c/Users/rajak/anaconda3/envs/ff/Library/mingw-w64/bin:/c/Users/rajak/anaconda3/envs/ff/Library/usr/bin:/c/Users/rajak/anaconda3/envs/ff/Library/bin:/c/Users/rajak/anaconda3/envs/ff/Scripts:/c/Users/rajak/anaconda3/envs/ff/bin:/c/Users/rajak/anaconda3/condabin:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/bin:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/libnvvp:/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/ProgramData/chocolatey/bin:/c/Program Files/NVIDIA Corporation/Nsight Compute 2019.4.0:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/extras/CUPTI/lib64:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include:/c/tools/cuda/bin:/c/tools/TensorRT-6.0.1.5:/c/Program Files/CMake/bin:/usr/bin:/c/opencv-master/cmake:.)
running develop
running egg_info
writing resample2d_cuda.egg-info\PKG-INFO
writing dependency_links to resample2d_cuda.egg-info\dependency_links.txt
writing top-level names to resample2d_cuda.egg-info\top_level.txt
reading manifest file 'resample2d_cuda.egg-info\SOURCES.txt'
writing manifest file 'resample2d_cuda.egg-info\SOURCES.txt'
running build_ext
C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\utils\cpp_extension.py:237: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'resample2d_cuda' extension
Emitting ninja build file D:\python\projects\reidentification\face_frontalization\frontalization-master\2_FFWM-master\cuda\resample2d_package\build\temp.win-amd64-3.7\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -IC:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\include -IC:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\include\TH -IC:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -IC:\Users\rajak\anaconda3\envs\ff\include -IC:\Users\rajak\anaconda3\envs\ff\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c D:\python\projects\reidentification\face_frontalization\frontalization-master\2_FFWM-master\cuda\resample2d_package\resample2d_cuda.cc /FoD:\python\projects\reidentification\face_frontalization\frontalization-master\2_FFWM-master\cuda\resample2d_package\build\temp.win-amd64-3.7\Release\resample2d_cuda.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=resample2d_cuda -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
FAILED: D:/python/projects/reidentification/face_frontalization/frontalization-master/2_FFWM-master/cuda/resample2d_package/build/temp.win-amd64-3.7/Release/resample2d_cuda.obj
cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -IC:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\include -IC:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\include\TH -IC:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -IC:\Users\rajak\anaconda3\envs\ff\include -IC:\Users\rajak\anaconda3\envs\ff\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c D:\python\projects\reidentification\face_frontalization\frontalization-master\2_FFWM-master\cuda\resample2d_package\resample2d_cuda.cc /FoD:\python\projects\reidentification\face_frontalization\frontalization-master\2_FFWM-master\cuda\resample2d_package\build\temp.win-amd64-3.7\Release\resample2d_cuda.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=resample2d_cuda -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
CreateProcess failed: The system cannot find the file specified.
ninja: fatal: ReadFile: The handle is invalid.

Traceback (most recent call last):
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\utils\cpp_extension.py", line 1400, in _run_ninja_build    check=True)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    'build_ext': BuildExtension
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\rajak\anaconda3\envs\ff\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\setuptools\command\develop.py", line 34, in run
    self.install_for_development()
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\setuptools\command\develop.py", line 136, in install_for_development
    self.run_command('build_ext')
  File "C:\Users\rajak\anaconda3\envs\ff\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\utils\cpp_extension.py", line 580, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\rajak\anaconda3\envs\ff\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\distutils\command\build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\utils\cpp_extension.py", line 562, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\utils\cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "C:\Users\rajak\anaconda3\envs\ff\lib\site-packages\torch\utils\cpp_extension.py", line 1413, in _run_ninja_build    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension
.........

**Comment by csyxwei** [comment]
It seems that you build this module with windows, and I only tested the code with Linux.

This issue may helpful for you [#20](https://github.com/RenYurui/Global-Flow-Local-Attention/issues/20) [#4](https://github.com/RenYurui/Global-Flow-Local-Attention/issues/4).

**Comment by ujwalakoriraj** [comment]
Thank you very much. I am going to try them.
